### ISSUE TITLE
What is the difference of selenoid/vnc_chrome:87.0 and cdtp/chrome:87.0

### ISSUE THREAD

**Issue by manikandan-manogar-19914** [aerokube/chrome-developer-tools-protocol-java-example#3]
I am now using selenoid/vnc_chrome:87.0 for my devtool testing. Now only I came to know the special image for devtool testing name cdtp/chrome:87.0.

@vania-pooh Kindly give the cdtp/chrome:87.0 image use case and information

Thanks in advance

**Comment by vania-pooh** [comment]
@Manikandan-18 CDTP image is now only compatible with Moon (https://aerokube.com/moon/latest/#_accessing_chrome_developer_tools).

**Comment by manikandan-manogar-19914** [comment]
Ok, thanks for the info @vania-pooh 👍
